/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package kitsunefox.musicmod;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class MusicmodModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public MusicmodModElements() {
		sounds.put(new ResourceLocation("musicmod", "guitar_fret1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fret1")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fret2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fret2")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fret3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fret3")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fret4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fret4")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fret5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fret5")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fret6"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fret6")));
		sounds.put(new ResourceLocation("musicmod", "guitar_cmajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_cmajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_cmajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_cmajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_csharpmajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_csharpmajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_csharpmajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_csharpmajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dmajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dmajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dmajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dmajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dsharpmajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dsharpmajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dsharpmajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dsharpmajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_emajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_emajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_emajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_emajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fmajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fmajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fmajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fmajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fsharpmajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fsharpmajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fsharpmajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fsharpmajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gmajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gmajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gmajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gmajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gsharpmajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gsharpmajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gsharpmajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gsharpmajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_amajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_amajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_amajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_amajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_asharpmajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_asharpmajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_bmajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_bmajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_bmajor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_bmajor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_cminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_cminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_cminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_cminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_csharpminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_csharpminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_csharpminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_csharpminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dsharpminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dsharpminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dsharpminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dsharpminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_eminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_eminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_eminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_eminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fsharpminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fsharpminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fsharpminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fsharpminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gsharpminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gsharpminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gsharpminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gsharpminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_aminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_aminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_aminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_aminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_asharpmajor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_asharpmajor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_asharpminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_asharpminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_asharpminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_asharpminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_bminor_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_bminor_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_bminor_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_bminor_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_cmajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_cmajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_cmajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_cmajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_csharpmajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_csharpmajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_csharpmajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_csharpmajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dmajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dmajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dmajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dmajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dsharpmajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dsharpmajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_dsharpmajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_dsharpmajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_emajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_emajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_emajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_emajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fmajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fmajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fmajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fmajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fsharpmajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fsharpmajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fsharpmajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fsharpmajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gmajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gmajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gmajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gmajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gsharpmajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gsharpmajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_gsharpmajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_gsharpmajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_amajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_amajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_amajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_amajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_asharpmajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_asharpmajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_asharpmajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_asharpmajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_bmajor7_down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_bmajor7_down")));
		sounds.put(new ResourceLocation("musicmod", "guitar_bmajor7_up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_bmajor7_up")));
		sounds.put(new ResourceLocation("musicmod", "guitar_fretnoise"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_fretnoise")));
		sounds.put(new ResourceLocation("musicmod", "piano_lower"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "piano_lower")));
		sounds.put(new ResourceLocation("musicmod", "piano_mid"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "piano_mid")));
		sounds.put(new ResourceLocation("musicmod", "piano_higher"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "piano_higher")));
		sounds.put(new ResourceLocation("musicmod", "piano_highest"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "piano_highest")));
		sounds.put(new ResourceLocation("musicmod", "guitar_lower"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_lower")));
		sounds.put(new ResourceLocation("musicmod", "guitar_mid"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_mid")));
		sounds.put(new ResourceLocation("musicmod", "guitar_higher"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_higher")));
		sounds.put(new ResourceLocation("musicmod", "guitar_highest"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "guitar_highest")));
		sounds.put(new ResourceLocation("musicmod", "bass_lower"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "bass_lower")));
		sounds.put(new ResourceLocation("musicmod", "bass_mid"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "bass_mid")));
		sounds.put(new ResourceLocation("musicmod", "bass_higher"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "bass_higher")));
		sounds.put(new ResourceLocation("musicmod", "bass_highest"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "bass_highest")));
		sounds.put(new ResourceLocation("musicmod", "bassdrum"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "bassdrum")));
		sounds.put(new ResourceLocation("musicmod", "closedhihat"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "closedhihat")));
		sounds.put(new ResourceLocation("musicmod", "floortom"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "floortom")));
		sounds.put(new ResourceLocation("musicmod", "openhihat"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "openhihat")));
		sounds.put(new ResourceLocation("musicmod", "ride"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "ride")));
		sounds.put(new ResourceLocation("musicmod", "snare"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "snare")));
		sounds.put(new ResourceLocation("musicmod", "snarecrossstick"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "snarecrossstick")));
		sounds.put(new ResourceLocation("musicmod", "tomtom"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "tomtom")));
		sounds.put(new ResourceLocation("musicmod", "hihat_kick"), new net.minecraft.util.SoundEvent(new ResourceLocation("musicmod", "hihat_kick")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("musicmod").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == MusicmodModElements.ModElement.class)
						elements.add((MusicmodModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(MusicmodModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new MusicmodModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		MusicmodMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final MusicmodModElements elements;
		protected final int sortid;

		public ModElement(MusicmodModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
